name = "DifferentialEquations"
uuid = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "8.0.0"

[deps]
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"

[compat]
OrdinaryDiffEq = "6.53"
Reexport = "1.0"
SciMLBase = "2.51"
julia = "1.10"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random", "SafeTestsets"]
